services: 
  zookeeper:
    network_mode: host
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    container_name: poc-zookeeper
    restart: unless-stopped
    environment:
      ZOO_TICK_TIME: 2000
      ZOO_ADMIN_SERVER_PORT_NUMBER: 8100
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    network_mode: host
    image: bitnami/kafka:latest
    hostname: broker
    container_name: poc-kafka
    restart: unless-stopped
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT 
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ENABLE_KRAFT: no
      KAFKA_MESSAGE_MAX_BYTES: 2147483647
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2147483647